---
- name: install the virtualenv requirements (Red Hat)
  yum:
    name:
    - python3-virtualenv
    - gcc
    - python3-devel
    - openssl-devel
    - libffi-devel
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version is version('8', '>=')
  tags:
  - install

- name: install the virtualenv requirements (Red Hat)
  yum:
    name:
    - python-virtualenv
    - gcc
    - python-devel
    - openssl-devel
    - libffi-devel
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version is version('8', '<')
  tags:
  - install

- name: install virtualenv (MacOS)
  pip:
    name: virtualenv
    state: present
  when: ansible_os_family == 'Darwin'
  tags:
  - install

- name: install pyOpenSSL and boto in a virtualenv (Red Hat/ MacOS)
  pip:
    name: "{{ ler53_item.name }}"
    state: "{{ ler53_item.state | default(omit) }}"
    version: "{{ ler53_item.version | default(omit) }}"
    virtualenv: "{{ ler53_account_key_dir }}/ansible-lets-encrypt-virtualenv"
    # This is required for libselinux-python
    virtualenv_site_packages: yes
  with_items:
  # Update setuptools
  - name: setuptools>44.0.0,<45.0.0
    state: present
  - name: pyOpenSSL
  - name: boto3
  - name: enum34
  - name: ipaddress
  - name: cffi
  loop_control:
    loop_var: ler53_item
  tags:
  - install

- name: use the created virtualenv
  set_fact:
    ansible_python_interpreter: "{{ ler53_account_key_dir }}/ansible-lets-encrypt-virtualenv/bin/python"
  tags:
  - install
